name: frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

# ===============================================================
# ======= CONFIGURACIÓN PARA EL ÍCONO DE LA APLICACIÓN ========
# ===============================================================
flutter_launcher_icons:
  # --- Configuración General ---
  android: true
  ios: true
  # Este es el ícono principal (cuadrado) para iOS y versiones viejas de Android.
  image_path: "assets/icon.png" 
  min_sdk_android: 21

  # --- Íconos Adaptativos (Soluciona el problema del círculo azul) ---
  # Color de fondo del ícono. Puedes usar un color hexadecimal.
  adaptive_icon_background: "#FFFFFF" # Fondo Blanco
  # Tu logo con fondo TRANSPARENTE. Esta es la capa de enfrente.
  adaptive_icon_foreground: "assets/icon.png"

# ===============================================================
# =========== CONFIGURACIÓN GENERAL DE FLUTTER ==================
# ===============================================================
flutter:
  uses-material-design: true

  # Asegúrate de que la carpeta 'assets' esté declarada aquí.
  assets:
    - assets/